promocode/promocode/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('promotions/', include('promotions.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

promocode/promotions/urls.py
from django.urls import path
from promotions.views import PromotionListView, promotion_detail, create_promotion

app_name = 'promotions'

urlpatterns = [
    path('', PromotionListView.as_view(), name='promotions_list'),
    path('create/', create_promotion, name='promotions_create'),
    path('<int:pk>/', promotion_detail, name='promotion_detail'),
]

promocode/users/urls.py
from django.urls import path
from .views import criar_cliente, login_cliente, logout_user

app_name = 'users'

urlpatterns = [
    path('register/', criar_cliente, name='register_user'),
    path('login/', login_cliente, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
]

promocode/promotions/models.py
from django.db import models
from django.contrib.auth import get_user_model

user_model = get_user_model()

class Promotion(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    url = models.URLField() 

    user = models.ForeignKey(user_model, on_delete=models.PROTECT)

class Comment(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()

    user = models.ForeignKey(user_model, on_delete=models.PROTECT)
    promotion = models.ForeignKey(Promotion, on_delete=models.PROTECT)

promocode/promotions/models/comment.py
from django.db import models
from django.contrib.auth import get_user_model
from .promotion import Promotion

user_model = get_user_model()

class Comment(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()

    user = models.ForeignKey(user_model, on_delete=models.PROTECT)
    promotion = models.ForeignKey(Promotion, on_delete=models.PROTECT)

    def __str__(self) -> str:
        return self.title

promocode/promotions/models/promotion.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _


user_model = get_user_model()

class Promotion(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('Titulo'))
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    url = models.URLField() 

    user = models.ForeignKey(user_model, on_delete=models.PROTECT)

    def __str__(self) -> str:
        return f'{self.title} - {self.price}'

promocode/users/models.py
from django.db import models

# Create your models here.

promocode/promotions/forms.py
from django import forms
from .models.promotion import Promotion

class MyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
      
       for visible in self.visible_fields():
           visible.field.widget.attrs['class'] = 'form-control'
  


class CreatePromotionForm(MyForm):
    class Meta:
        model = Promotion
        fields = ['title', 'description', 'url', 'price']

promocode/promotions/views.py
from django.shortcuts import render, redirect
from promotions.models.promotion import Promotion
from .forms import CreatePromotionForm
from django.contrib import messages
from django.views.generic import ListView

class PromotionListView(ListView):
    model = Promotion
    template_name = 'promotions/index.html'
    context_object_name = 'promotions'


# def promotions_list(request):
#     promotions = Promotion.objects.all()
#     context  = {
#         'promotions': promotions,
#     }
#     return render(request, 'promotions/index.html', context)


# PATH PARAM
def promotion_detail(request, pk):
    promotion = Promotion.objects.get(pk=pk)
    return render(request, 'promotions/detail.html', {
        'promotion': promotion
    })

def create_promotion(request):
    if request.method == 'POST':
        promotion_form = CreatePromotionForm(request.POST)
        if promotion_form.is_valid():
            promotion = promotion_form.save(commit=False)
            promotion.user = request.user
            promotion.save()
            messages.add_message(request, messages.SUCCESS, 'Promoção criada com sucesso!')
            return redirect('promotions:promotions_list')
    else:
        promotion_form = CreatePromotionForm()

    return render(request, 'promotions/create.html', {
        'form': promotion_form
    })

promocode/users/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect

def criar_cliente(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = get_user_model()
        user_created = user.objects.create(
            email=email,
            username=username
        )

        user_created.set_password(password)

        user_created.save()

    return render(request, 'users/register.html')


def login_cliente(request):
    if request.user.is_authenticated:
        return redirect('promotions:promotions_list')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect('promotions:promotions_list')
    
    return render(request, 'users/login.html')
            
def logout_user(request):
    logout(request)
    return redirect('promotions:promotions_list')

promocode/promotions/templates/promotions/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="container">
            <h1>Criar Promoção</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-success w-100 mt-4">Criar</button>
            </form>
        </div>
    </main>
{% endblock %}

promocode/promotions/templates/promotions/detail.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h1>{{ promotion.title }} </h1>
        <h1>{{ promotion.description }} </h1>
        <p>{{ promotion.price }}</p>
        <a href="{{promotion.url}}">Ir Para</a>
    </main>
{% endblock %}

promocode/promotions/templates/promotions/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {{categories}}
    {% if user.is_authenticated %}
    <a href="{% url 'promotions:promotions_create' %}" class="btn btn-primary w-100">Cadastrar Promoção</a>
    {% endif %}
    <div class="row">
        {% for promotion in promotions %}
        <div class="col-12 mt-2">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{promotion.title}}</h5>
                    <p class="card-text">
                        <h1>
                            {{promotion.price}} R$
                        </h1>
                    </p>
                    <a href="{% url 'promotions:promotion_detail' promotion.pk %}" class="card-link">Detalhes</a>
                    <a href="{{promotion.url}}" class="card-link" target="_blank">Acessar Promoção</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

promocode/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promocode</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbarr</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                {{user.email}}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout_user' %}">Sair</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register_user' %}">Registrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login_user' %}">Entrar</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <main class="pt-5">
        {% block content %}{% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

promocode/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Entrar</h1>
    <hr>
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="username" id="username" placeholder="Digite seu username">
        <input type="password" name="password" id="password" placeholder="Digite sua senha">
        <input type="submit" value="Entrar" class="btn btn-primary">
    </form>
</div>
{% endblock %}

promocode/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Registrar Usuario</h1>
    <hr>
    <form method="POST">
        {% csrf_token %}
        <input type="email" name="email" id="email" placeholder="Digite seu email">
        <input type="text" name="username" id="username" placeholder="Digite seu username">
        <input type="password" name="password" id="password" placeholder="Digite sua senha">
        <input type="submit" value="Registrar">
    </form>
</div>
{% endblock %}